# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "daeconv"
COPYRIGHT = ""

ENV['SCALA_HOME'] = '/Users/schuller/scala/scala-2.8.0.r20331-b20100101020206'
ENV['USE_FSC'] = 'yes'
require 'buildr/scala'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Daeconv project"
define "daeconv" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
end
